### ISSUE TITLE
[BUG] Standard use does not work with MidiQoL if attack/damage are not auto-rolled

### ISSUE THREAD

**Issue by BadIdeasBureau** [p4535992/environment-interaction-multisystem#1]
**Module Version:** 1.2.0

**Describe the bug**
When using MidiQoL, and environment interaction which is not set to "ITEM ENVIRONMENT" will not allow the attack to be rolled from the chat card (as the item no longer exists on the actor at the point where that attack is clicked), and will pop an error that "the requested item (id) no longer exists on the actor (name)".  The attack will work as expected if attack and damage are auto-rolled, rather than triggered from the chat card

**To Reproduce**
Enable MidiQoL, without auto-roll attack
Set any attack as an environment interaction
Use the attack from another actor
Click the "attack" button on the chat card

**Expected behavior**
Some kind of integration with Midi, e.g. by persisting the item on the actor until the workflow completes.

**Screenshots**
![image](https://user-images.githubusercontent.com/36359784/172606841-cb203abd-819d-4818-95c6-1caa0ce92f96.png)

**Browser:**
 - Chrome

**Foundry Version:** 
9.269

**Game System:** 
dnd5e
**Additional context**
MidiQoL version 0.9.57, GM attack settings as below
![image](https://user-images.githubusercontent.com/36359784/172607526-c319deb6-5c27-4a77-af88-1bf936d38dc4.png)

**Comment by p4535992** [comment]
I can not find a "smart" solution to the problem, for now as an idiotic solution I have added a setting module to delay it by tot. seconds the deletion of the object so as to give time for the launch of the attack and damage from the chat.
I also put an integration with "Hurry up" to graphically show the time left before the deletion of the object
